.class public final Lcom/puddingstudio/cardgame/proto/CardProto;
.super Ljava/lang/Object;
.source "CardProto.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/puddingstudio/cardgame/proto/CardProto$1;,
        Lcom/puddingstudio/cardgame/proto/CardProto$slot_win_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$slot_win_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$slot_card_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$slot_card_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$daily_reward_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$daily_reward_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$pvp_reward_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$pvp_reward_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$event_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$event_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$upgrade_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$upgrade_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$attribute_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$attribute_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$exp_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$exp_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$player_exp_data;,
        Lcom/puddingstudio/cardgame/proto/CardProto$player_exp_dataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$leader_skill;,
        Lcom/puddingstudio/cardgame/proto/CardProto$leader_skillOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$passive_skill;,
        Lcom/puddingstudio/cardgame/proto/CardProto$passive_skillOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$buff;,
        Lcom/puddingstudio/cardgame/proto/CardProto$buffOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$active_skill;,
        Lcom/puddingstudio/cardgame/proto/CardProto$active_skillOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMapData;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMapDataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$enemy_group;,
        Lcom/puddingstudio/cardgame/proto/CardProto$enemy_groupOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$boss_group;,
        Lcom/puddingstudio/cardgame/proto/CardProto$boss_groupOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBoss;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBossOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$last_map_result;,
        Lcom/puddingstudio/cardgame/proto/CardProto$last_map_resultOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$action_unit;,
        Lcom/puddingstudio/cardgame/proto/CardProto$action_unitOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCAchievement;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCAchievementOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTeam;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTeamOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCFriend;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCFriendOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCFragment;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCFragmentOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHero;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCCard;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCCardOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCPlayer;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCPlayerOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCActivityMapData;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCActivityMapDataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCRedisTeamData;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCRedisTeamDataOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCPVPTeamInfo;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCPVPTeamInfoOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTestTeamResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTestTeamResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTestTeamRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTestTeamRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCUploadDataRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCUploadDataRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCKickPlayerResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCKickPlayerResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCClaimPVPRewardResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCClaimPVPRewardResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCClaimPVPRewardRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCClaimPVPRewardRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetBattleVideoRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetBattleVideoRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRewardDataResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRewardDataResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRewardDataRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRewardDataRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRankByIdResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRankByIdResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRankByIdRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRankByIdRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRankResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRankResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRankRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPRankRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPOpponentResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPOpponentResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPOpponentRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetPVPOpponentRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCDecomposeFragmentResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCDecomposeFragmentResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCDecomposeFragmentRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCDecomposeFragmentRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCCombineFragmentResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCCombineFragmentResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCCombineFragmentRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCCombineFragmentRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCReBindFacebookResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCReBindFacebookResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCReBindFacebookRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCReBindFacebookRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBindFacebookResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBindFacebookResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBindFacebookRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBindFacebookRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCUploadMainHeroResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCUploadMainHeroResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCUploadMainHeroRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCUploadMainHeroRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCFetchActivityMapDataResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCFetchActivityMapDataResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCFetchActivityMapDataRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCFetchActivityMapDataRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGooglePlusBattleRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGooglePlusBattleRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCArenaResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCArenaResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCArenaRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCArenaRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetAchievementResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetAchievementResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetAchievementRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetAchievementRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCDailyTask;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCDailyTaskOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCClaimAchievementResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCClaimAchievementResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCClaimAchievementRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCClaimAchievementRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBuyItemResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBuyItemResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBuyItemRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBuyItemRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCSlotCardResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCSlotCardResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCSlotCardRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCSlotCardRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCManageFriendResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCManageFriendResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCManageFriendRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCManageFriendRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetFriendAddListResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetFriendAddListResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetFriendAddListRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetFriendAddListRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetRandomPlayerResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetRandomPlayerResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetRandomPlayerRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetRandomPlayerRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCSearchFriendResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCSearchFriendResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCSearchFriendRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCSearchFriendRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetFriendListResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetFriendListResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetFriendListRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetFriendListRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetMessageListResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetMessageListResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetMessageListRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetMessageListRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCConfirmSysMessageResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCConfirmSysMessageResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCConfirmSysMessageRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCConfirmSysMessageRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCWorldMessageList;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCWorldMessageListOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCWorldMessage;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCWorldMessageOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCInstantMessage;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCInstantMessageOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCChangeUserNameResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCChangeUserNameResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCChangeUserNameRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCChangeUserNameRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroSellResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroSellResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroSellRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroSellRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroUpgradeResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroUpgradeResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroUpgradeRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroUpgradeRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroUpdateResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroUpdateResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroUpdateRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeroUpdateRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCRetreatResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCRetreatResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCRetreatRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCRetreatRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMapResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMapResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBattleResult;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCBattleResultOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCAtkReward;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCAtkRewardOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCRound;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCRoundOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCAtkItem;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCAtkItemOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCWipeResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCWipeResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCWipeRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCWipeRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMapClearReward;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMapClearRewardOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMapRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMapRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCLogoutResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCLogoutResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCLogoutRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCLogoutRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTeamComposeResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTeamComposeResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTeamComposeRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCTeamComposeRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetGiftHeroResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetGiftHeroResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetGiftHeroRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetGiftHeroRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMainHeroResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMainHeroResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMainHeroRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCMainHeroRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetAllFriendInfoResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetAllFriendInfoResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetAllFriendInfoRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCGetAllFriendInfoRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCLoginResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCLoginResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCLoginRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCLoginRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeartbeatResponse;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeartbeatResponseOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeartbeatRequest;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCHeartbeatRequestOrBuilder;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCStatus;,
        Lcom/puddingstudio/cardgame/proto/CardProto$CCStatusOrBuilder;
    }
.end annotation


# direct methods
.method static constructor <clinit>()V
    .locals 0

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    .prologue
    .line 7
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static registerAllExtensions(Lcom/google/protobuf/ExtensionRegistryLite;)V
    .locals 0
    .param p0, "registry"    # Lcom/google/protobuf/ExtensionRegistryLite;

    .prologue
    .line 10
    return-void
.end method
