.class public Lcom/sponsorpay/utils/UserId;
.super Ljava/lang/Object;
.source "UserId.java"


# static fields
.field public static final STATE_GENERATED_USERID_KEY:Ljava/lang/String; = "STATE_GENERATED_USERID_KEY"


# direct methods
.method public constructor <init>()V
    .locals 0

    .prologue
    .line 17
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method private static generateUserId()Ljava/lang/String;
    .locals 4

    .prologue
    .line 40
    new-instance v1, Ljava/lang/StringBuilder;

    invoke-direct {v1}, Ljava/lang/StringBuilder;-><init>()V

    .line 42
    .local v1, "builder":Ljava/lang/StringBuilder;
    invoke-static {}, Ljava/util/UUID;->randomUUID()Ljava/util/UUID;

    move-result-object v3

    invoke-virtual {v1, v3}, Ljava/lang/StringBuilder;->append(Ljava/lang/Object;)Ljava/lang/StringBuilder;

    .line 44
    invoke-virtual {v1}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;

    move-result-object v0

    .line 45
    .local v0, "baseText":Ljava/lang/String;
    invoke-static {v0}, Lcom/sponsorpay/utils/SignatureTools;->generateSHA1ForString(Ljava/lang/String;)Ljava/lang/String;

    move-result-object v2

    .line 47
    .local v2, "generatedId":Ljava/lang/String;
    if-eqz v2, :cond_0

    const-string v3, "nosha1"

    invoke-virtual {v2, v3}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z

    move-result v3

    if-eqz v3, :cond_1

    .line 48
    :cond_0
    move-object v2, v0

    .line 51
    :cond_1
    return-object v2
.end method

.method public static declared-synchronized getAutoGenerated(Landroid/content/Context;)Ljava/lang/String;
    .locals 6
    .param p0, "context"    # Landroid/content/Context;

    .prologue
    .line 22
    const-class v4, Lcom/sponsorpay/utils/UserId;

    monitor-enter v4

    .line 23
    :try_start_0
    const-string v3, "SponsorPayPublisherState"

    const/4 v5, 0x0

    .line 22
    invoke-virtual {p0, v3, v5}, Landroid/content/Context;->getSharedPreferences(Ljava/lang/String;I)Landroid/content/SharedPreferences;

    move-result-object v0

    .line 25
    .local v0, "state":Landroid/content/SharedPreferences;
    const-string v3, "STATE_GENERATED_USERID_KEY"

    const/4 v5, 0x0

    invoke-interface {v0, v3, v5}, Landroid/content/SharedPreferences;->getString(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;

    move-result-object v2

    .line 27
    .local v2, "userIdValue":Ljava/lang/String;
    if-nez v2, :cond_0

    .line 29
    invoke-static {}, Lcom/sponsorpay/utils/UserId;->generateUserId()Ljava/lang/String;

    move-result-object v2

    .line 31
    invoke-interface {v0}, Landroid/content/SharedPreferences;->edit()Landroid/content/SharedPreferences$Editor;

    move-result-object v1

    .line 32
    .local v1, "stateEditor":Landroid/content/SharedPreferences$Editor;
    const-string v3, "STATE_GENERATED_USERID_KEY"

    invoke-interface {v1, v3, v2}, Landroid/content/SharedPreferences$Editor;->putString(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;

    .line 33
    invoke-interface {v1}, Landroid/content/SharedPreferences$Editor;->commit()Z
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_0

    .line 36
    .end local v1    # "stateEditor":Landroid/content/SharedPreferences$Editor;
    :cond_0
    monitor-exit v4

    return-object v2

    .line 22
    .end local v0    # "state":Landroid/content/SharedPreferences;
    .end local v2    # "userIdValue":Ljava/lang/String;
    :catchall_0
    move-exception v3

    monitor-exit v4

    throw v3
.end method
